/*
 * Generates src/environments/version.ts at build time.
 *
 * The build number is the git commit count (`git rev-list --count HEAD`), which
 * increments automatically on every commit — no manual bump needed. The major.minor
 * prefix comes from package.json (bump that only for real releases).
 *
 * This file is git-ignored and regenerated on install + every build, so it never
 * needs to be committed.
 */
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const pkg = require(path.join(__dirname, '..', 'package.json'));

const sh = (cmd) => {
  try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return ''; }
};

const base    = pkg.version.split('.').slice(0, 2).join('.'); // "1.0" from package.json
const build   = sh('git rev-list --count HEAD') || '0';        // auto-incrementing build number
const commit  = sh('git rev-parse --short HEAD') || 'local';
const version = `${base}.${build}`;                            // e.g. "1.0.247"

const outPath = path.join(__dirname, '..', 'src', 'environments', 'version.ts');
const content = `// AUTO-GENERATED by scripts/generate-version.js at build time — do not edit, do not commit.
export const VERSION = {
  version: '${version}',
  commit: '${commit}',
  buildDate: '${new Date().toISOString()}',
};
`;

fs.writeFileSync(outPath, content);
console.log(`[version] stamped v${version} (${commit})`);
